config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: :true
  validates :content, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                   format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path, notice: "ブログを投稿しました！"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
     redirect_to blogs_path, notice: "ブログを編集しました！"
    else
     render 'edit'
   end
  end

  def show
   @blog = Blog.find(params[:id])
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "ブログを削除しました！"
  end

  private
  def blog_params
    params.require(:blog).permit(:title,:content, :user_id)
  end

  def set_blog
     @blog = Blog.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
 <% if @blog.errors.any? %>
   <div id="error_explanation">
     <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
     <ul>

     <% @blog.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

 <div class="blog_title">
   <%= form.label :title %>
   <%= form.text_field :title %>
 </div>
 <div class="blog_title">
   <%= form.label :content %>
   <%= form.text_field :content %>
 </div>
 <%= form.submit %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<table>
 <tr>
   <th>タイトル</th>
   <th>内容</th>
 </tr>

<% @blogs.each do |blog| %>
 <tr>
   <td><%= blog.title %></td>
   <td><%= blog.content %></td>
   <td><%= link_to '詳細を確認する', blog_path(blog.id) %></td>
   <td><%= link_to "ブログを編集する", edit_blog_path(blog.id) %></td>
   <td><%= link_to "ブログを削除する", blog_path(blog.id), method: :delete %></td>
 </tr>
<% end %>
</table>

<br>

<%= link_to '新しくブログを投稿する', new_blog_path %>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true  ) do |form| %>
 <% if @blog.errors.any? %>
   <div id="error_explanation">
     <h2><%= @photo.errors.count %>件のエラーがあります。</h2>
     <ul>

     <% @blog.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

 <div class="title">
   <%= form.label :title %>
   <%= form.text_field :title %>
 </div>
 <div class="_content">
   <%= form.label :content %>
   <%= form.text_field :content %>
 </div>

 <%= form.submit %>
<% end %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>